global:
  scrape_interval: 3s

  external_labels:
    monitor: "example-monitor"

rule_files:

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["registration:5000"]

  - job_name: flower
    static_configs:
      - targets: ['flower:5555']
