global:
  scrape_interval: 3s

  external_labels:
    monitor: "example-monitor"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "app"
    static_configs:
      - targets: ["registration:5000"]